### ISSUE TITLE
完成点赞业务功能代码

### ISSUE THREAD

**Issue by xffvip** [xffvip/work#4]
完成点赞业务功能代码
- 用户点赞功能
- 统计点赞数量
- 使用redis实现

**Comment by 08820048** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by xffvip** [comment]
> 完成点赞业务功能代码
> 
> * 用户点赞功能
> * 统计点赞数量
> * 使用redis实现
